### ISSUE TITLE
Add Makefile 

### ISSUE THREAD

**Issue by sashayakovtseva** [Lighty0410/ekadashi-server#14]
Required targets: build, clean, test, lint

**Comment by Lighty0410** [comment]
Create Makefile. Disable all except 
    go vet - Reports potential errors that otherwise compile.
    gotype - Syntactic and semantic analysis similar to the Go compiler.
    deadcode - Finds unused code.
    gocyclo - Computes the cyclomatic complexity of functions.
    golint - Google's (mostly stylistic) linter.
    varcheck - Find unused global variables and constants.
    structcheck - Find unused struct fields.
    maligned - Detect structs that would take less memory if their fields were sorted.
    errcheck - Check that error return values are used.
    staticcheck - Statically detect bugs, both obvious and subtle ones.
    ineffassign - Detect when assignments to existing variables are not used.
    interfacer - Suggest narrower interfaces that can be used.
    unconvert - Detect redundant type conversions.
    goconst - Finds repeated strings that could be replaced by a constant.
    gofmt -s - Checks if the code is properly formatted and could not be further simplified.
    goimports - Checks missing or unreferenced package imports.
    lll - Report long lines (see --line-length=N).
    misspell - Finds commonly misspelled English words.
    unparam - Find unused function parameters
Learn about https://godoc.org/github.com/stretchr/testify/require and https://godoc.org/github.com/stretchr/testify/assert and write mongo test.
